=== stoplightio/formtron/formtron-schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://npmjs.org/package/formtron",
  "$ref": "#/definitions/form",
  "definitions": {
    "_primitive": {
      "type": "object",
      "required": ["title", "type"],
      "properties": {
        "type": {
          "type": "string"
        },
        "title": {
          "type": "string"
        },
        "custom": {}
      },
      "additionalProperties": true
    },
    "field": {
      "anyOf": [
        { "$ref": "#/definitions/_primitive" },
        { "$ref": "#/definitions/array" },
        { "$ref": "#/definitions/object" },
        { "$ref": "#/definitions/form" }
      ]
    },
    "form": {
      "type": "object",
      "required": ["title", "type", "fields"],
      "properties": {
        "$schema": {
          "type": "string"
        },
        "type": {
          "type": "string",
          "enum": ["form"]
        },
        "title": {
          "type": "string"
        },
        "path": {
          "type": "string"
        },
        "description": {
          "type": "string"
        },
        "fields": {
          "type": "object",
          "additionalProperties": { "$ref": "#/definitions/field" }
        },
        "custom": {}
      },
      "additionalProperties": false
    },
    "array": {
      "type": "object",
      "required": ["title", "type", "items"],
      "properties": {
        "type": {
          "type": "string",
          "enum": ["array"]
        },
        "title": {
          "type": "string"
        },
        "path": {
          "type": "string"
        },
        "default": {},
        "items": { "$ref": "#/definitions/field" },
        "custom": {}
      },
      "additionalProperties": false
    },
    "object": {
      "type": "object",
      "required": ["title", "type", "keys", "values"],
      "properties": {
        "type": {
          "type": "string",
          "enum": ["object"]
        },
        "title": {
          "type": "string"
        },
        "path": {
          "type": "string"
        },
        "default": {},
        "keys": { "$ref": "#/definitions/field" },
        "values": { "$ref": "#/definitions/field" },
        "custom": {}
      },
      "additionalProperties": false
    }
  }
}

=== stoplightio/formtron/src/__stories__/examples/enable/schema.json
{
  "$schema": "../../../../ui-schema.json",
  "type": "form",
  "title": "Security",
  "description": "A shared security scheme definition",
  "fields": {
    "securityDefinitions.?": {
      "type": "string",
      "title": "securityId"
    },
    "securityDefinitions.*.type": {
      "type": "select",
      "title": "Type",
      "options": ["basic", "apiKey", "oauth2"]
    },
    "securityDefinitions.*.description": {
      "type": "string",
      "title": "Description"
    },
    "securityDefinitions.*.name": {
      "type": "string",
      "title": "Name",
      "enabled": "type === 'apiKey'"
    },
    "securityDefinitions.*.in": {
      "type": "select",
      "title": "In",
      "options": ["query", "header"],
      "enabled": "type === 'apiKey'"
    },
    "securityDefinitions.*.flow": {
      "type": "select",
      "title": "Flow",
      "options": ["implicit", "password", "application", "accessCode"],
      "enabled": "type === 'oauth2'"
    },
    "securityDefinitions.*.authorizationUrl": {
      "type": "string",
      "title": "Authorization URL",
      "enabled": "type === 'oauth2' && (flow === 'implicit' || flow === 'accessCode')"
    },
    "securityDefinitions.*.tokenUrl": {
      "type": "string",
      "title": "Token URL",
      "enabled": "type === 'oauth2' && (flow === 'password' || flow === 'application' || flow === 'accessCode')"
    },
    "securityDefinitions.*.scopes": {
      "type": "object",
      "title": "Scopes",
      "default": "",
      "keys": {
        "type": "string",
        "title": "Name"
      },
      "values": {
        "type": "string",
        "title": "Description"
      },
      "enabled": "type === 'oauth2'"
    }
  }
}

=== stoplightio/formtron/src/__tests__/examples/complex/schema.json
{
  "$schema": "../../../../ui-schema.json",
  "type": "form",
  "title": "HTTP Response",
  "description": "HTTP Response",
  "fields": {
    "paths.*.*.responses.?": {
      "type": "integer",
      "title": "Code",
      "custom": {
        "widget": "randomNumber"
      }
    },
    "paths.*.*.responses.*.description": {
      "type": "markdown",
      "title": "Description",
      "minLength": 4,
      "required": true
    },
    "paths.*.*.responses.*.content": {
      "type": "json",
      "title": "Content"
    },
    "paths.*.*.responses.*.headers": {
      "type": "array",
      "title": "Headers",
      "default": {
        "name": "",
        "type": "bug",
        "format": "json",
        "default": "",
        "description": ""
      },
      "items": {
        "title": "Header",
        "type": "form",
        "fields": {
          "name": {
            "type": "string",
            "title": "Name",
            "path": "name"
          },
          "type": {
            "type": "select",
            "title": "Type",
            "path": "type",
            "options": ["bug", "hot", "cold"]
          },
          "format": {
            "type": "select",
            "title": "Format",
            "path": "format",
            "options": ["json", "hot", "cold"]
          },
          "default": {
            "type": "string",
            "title": "Default",
            "path": "default"
          },
          "description": {
            "type": "string",
            "title": "Description",
            "path": "description"
          }
        }
      }
    },
    "paths.*.*.responses.*.schema": {
      "type": "multiselect",
      "title": "Schema",
      "custom": {
        "source": "models"
      }
    },
    "paths.*.*.responses.*.examples": {
      "type": "object",
      "title": "Examples",
      "default": {},
      "keys": {
        "type": "string",
        "title": "Name"
      },
      "values": {
        "type": "json",
        "title": "Content"
      }
    }
  }
}

=== stoplightio/formtron/src/__stories__/examples/show/schema.json
{
  "$schema": "../../../../ui-schema.json",
  "type": "form",
  "title": "Security",
  "description": "A shared security scheme definition",
  "fields": {
    "securityDefinitions.?": {
      "type": "string",
      "title": "securityId"
    },
    "securityDefinitions.*.type": {
      "type": "select",
      "title": "Type",
      "options": ["basic", "apiKey", "oauth2"]
    },
    "securityDefinitions.*.description": {
      "type": "string",
      "title": "Description"
    },
    "securityDefinitions.*.name": {
      "type": "string",
      "title": "Name",
      "show": "type === 'apiKey'"
    },
    "securityDefinitions.*.in": {
      "type": "select",
      "title": "In",
      "options": ["query", "header"],
      "show": "type === 'apiKey'"
    },
    "securityDefinitions.*.flow": {
      "type": "select",
      "title": "Flow",
      "options": ["implicit", "password", "application", "accessCode"],
      "show": "type === 'oauth2'"
    },
    "securityDefinitions.*.authorizationUrl": {
      "type": "string",
      "title": "Authorization URL",
      "show": "type === 'oauth2' && (flow === 'implicit' || flow === 'accessCode')"
    },
    "securityDefinitions.*.tokenUrl": {
      "type": "string",
      "title": "Token URL",
      "show": "type === 'oauth2' && (flow === 'password' || flow === 'application' || flow === 'accessCode')"
    },
    "securityDefinitions.*.scopes": {
      "type": "object",
      "title": "Scopes",
      "default": "",
      "keys": {
        "type": "string",
        "title": "Name"
      },
      "values": {
        "type": "string",
        "title": "Description"
      },
      "show": "type === 'oauth2'"
    }
  }
}

=== stoplightio/formtron/src/__tests__/examples/wildcards/schema.json
{
  "$schema": "../../../../ui-schema.json",
  "title": "Form (OASv2 Operation Node)",
  "description": "An HTTP operation.",
  "type": "form",
  "fields": {
    "paths.*.?": {
      "type": "select",
      "options": ["get", "post", "put", "delete", "options"],
      "title": "Method"
    },
    "paths.?.*": {
      "type": "string",
      "title": "path",
      "required": true
    },
    "paths.*.*.tags": {
      "type": "multiselect",
      "title": "Tag",
      "custom": {
        "source": "tags"
      }
    },
    "paths.*.*.taglist": {
      "title": "List of Tags",
      "type": "array",
      "default": [],
      "items": {
        "type": "multiselect",
        "title": "Tag",
        "options": ["Admin", "Todos"]
      }
    },
    "paths.*.*.description": {
      "type": "markdown",
      "title": "Description"
    }
  }
}

=== stoplightio/formtron/src/__stories__/examples/array/schema.json
{
  "$schema": "../../../../ui-schema.json",
  "title": "Arrays",
  "description": "Several types of arrays",
  "type": "form",
  "fields": {
    "paths.*.*.tags": {
      "type": "array",
      "title": "Strings",
      "default": "",
      "items": {
        "title": "Tag name",
        "type": "string"
      }
    },
    "paths.*.*.numbers": {
      "type": "array",
      "title": "Integers",
      "default": 0,
      "items": {
        "title": "Number",
        "type": "integer"
      }
    },
    "paths.*.*.schemes": {
      "type": "array",
      "title": "Multiselects",
      "default": [],
      "items": {
        "title": "Scheme",
        "type": "multiselect",
        "options": ["http", "https", "ws", "wss"]
      }
    }
  }
}

=== stoplightio/formtron/src/__stories__/examples/object/schema.json
{
  "$schema": "../../../../ui-schema.json",
  "title": "Objects",
  "description": "Several types of objects",
  "type": "form",
  "fields": {
    "paths.*.*.strings": {
      "type": "object",
      "title": "Strings",
      "keys": {
        "title": "Header",
        "type": "string"
      },
      "values": {
        "title": "Value",
        "type": "string"
      },
      "default": ""
    },
    "paths.*.*.numbers": {
      "type": "object",
      "title": "Integers",
      "keys": {
        "title": "Name",
        "type": "string"
      },
      "values": {
        "title": "Number",
        "type": "integer"
      },
      "default": 0
    },
    "paths.*.*.json": {
      "type": "object",
      "title": "Examples",
      "keys": {
        "title": "Status Code",
        "type": "integer"
      },
      "values": {
        "title": "Response",
        "type": "json"
      },
      "default": {}
    },
    "paths.*.*.select": {
      "type": "object",
      "title": "Select",
      "keys": {
        "title": "Method",
        "type": "select",
        "options": ["get", "post", "put", "delete", "options"]
      },
      "values": {
        "title": "Status Code",
        "type": "integer"
      },
      "default": 100
    },
    "paths.*.*.security": {
      "title": "Security",
      "type": "object",
      "keys": {
        "title": "Security Scheme",
        "type": "string"
      },
      "values": {
        "title": "OAuth2 Scopes",
        "type": "multiselect"
      },
      "default": []
    }
  }
}

=== stoplightio/formtron/src/__stories__/examples/evalOptions/schema.json
{
  "$schema": "../../../../ui-schema.json",
  "type": "form",
  "title": "Parameter",
  "description": "Describes a single parameter",
  "fields": {
    "paths.*.*.parameters.?": {
      "type": "string",
      "title": "parameterId",
      "required": true
    },
    "paths.*.*.parameters.*.name": {
      "type": "string",
      "title": "Name",
      "required": true
    },
    "paths.*.*.parameters.*.in": {
      "type": "select",
      "title": "In",
      "options": ["query", "header", "path", "formData", "body"],
      "required": true
    },
    "paths.*.*.parameters.*.description": {
      "type": "string",
      "title": "Description"
    },
    "paths.*.*.parameters.*.required": {
      "type": "checkbox",
      "title": "Required"
    },
    "paths.*.*.parameters.*.schema": {
      "type": "string",
      "title": "Schema",
      "show": "in === 'body'"
    },
    "paths.*.*.parameters.*.type": {
      "type": "select",
      "title": "Type",
      "evalOptions": "in === 'formData' ? ['string','number','integer','boolean','array','file'] : ['string','number','integer','boolean','array']",
      "show": "in !== 'body'"
    },
    "paths.*.*.parameters.*.format": {
      "type": "select",
      "title": "Format",
      "evalOptions": "type === 'integer' ? ['int32','int64'] : type === 'number' ? ['float','double'] : type === 'string' ? ['byte','binary','date','date-time','password'] : []",
      "strict": false
    },
    "paths.*.*.parameters.*.allowEmptyValue": {
      "type": "checkbox",
      "title": "Allow Empty",
      "show": "in === 'query' || in === 'formData'"
    },
    "paths.*.*.parameters.*.default": {
      "type": "string",
      "title": "Default"
    },
    "paths.*.*.parameters.*.items": {
      "type": "form",
      "title": "Items",
      "show": "type === 'array'",
      "fields": {
        "type": {
          "type": "select",
          "title": "Type",
          "options": [
            "string",
            "number",
            "integer",
            "boolean",
            "array"
          ]
        }
      }
    }
  }
}
