=== stoplightio/formtron/ui-schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://npmjs.org/package/formtron",
  "$ref": "#/definitions/form",
  "definitions": {
    "field": {
      "oneOf": [
        { "$ref": "#/definitions/string" },
        { "$ref": "#/definitions/integer" },
        { "$ref": "#/definitions/checkbox" },
        { "$ref": "#/definitions/select" },
        { "$ref": "#/definitions/multiselect" },
        { "$ref": "#/definitions/markdown" },
        { "$ref": "#/definitions/array" },
        { "$ref": "#/definitions/object" },
        { "$ref": "#/definitions/form" },
        { "$ref": "#/definitions/json" }
      ]
    },
    "form": {
      "type": "object",
      "required": ["title", "type", "fields"],
      "properties": {
        "$schema": {
          "type": "string"
        },
        "type": {
          "type": "string",
          "enum": ["form"]
        },
        "title": {
          "type": "string"
        },
        "path": {
          "type": "string"
        },
        "description": {
          "type": "string"
        },
        "fields": {
          "type": "object",
          "additionalProperties": { "$ref": "#/definitions/field" }
        },
        "custom": {}
      },
      "additionalProperties": false
    },
    "integer": {
      "type": "object",
      "required": ["title", "type"],
      "properties": {
        "type": {
          "type": "string",
          "enum": ["integer"]
        },
        "title": {
          "type": "string"
        },
        "path": {
          "type": "string"
        },
        "required": {
          "type": "boolean"
        },
        "custom": {}
      },
      "additionalProperties": false
    },
    "checkbox": {
      "type": "object",
      "required": ["title", "type"],
      "properties": {
        "type": {
          "type": "string",
          "enum": ["checkbox"]
        },
        "title": {
          "type": "string"
        },
        "path": {
          "type": "string"
        },
        "required": {
          "type": "boolean"
        },
        "custom": {}
      },
      "additionalProperties": false
    },
    "markdown": {
      "type": "object",
      "required": ["title", "type"],
      "properties": {
        "type": {
          "type": "string",
          "enum": ["markdown"]
        },
        "title": {
          "type": "string"
        },
        "path": {
          "type": "string"
        },
        "required": {
          "type": "boolean"
        },
        "minLength": {
          "type": "number"
        },
        "custom": {}
      },
      "additionalProperties": false
    },
    "json": {
      "type": "object",
      "required": ["title", "type"],
      "properties": {
        "type": {
          "type": "string",
          "enum": ["json"]
        },
        "title": {
          "type": "string"
        },
        "path": {
          "type": "string"
        },
        "custom": {}
      },
      "additionalProperties": false
    },
    "string": {
      "type": "object",
      "required": ["title", "type"],
      "properties": {
        "type": {
          "type": "string",
          "enum": ["string"]
        },
        "title": {
          "type": "string"
        },
        "path": {
          "type": "string"
        },
        "required": {
          "type": "boolean"
        },
        "minLength": {
          "type": "number"
        },
        "maxLength": {
          "type": "number"
        },
        "custom": {}
      },
      "additionalProperties": false
    },
    "select": {
      "type": "object",
      "required": ["title", "type"],
      "properties": {
        "type": {
          "type": "string",
          "enum": ["select"]
        },
        "title": {
          "type": "string"
        },
        "path": {
          "type": "string"
        },
        "required": {
          "type": "boolean"
        },        
        "options": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "custom": {}
      },
      "additionalProperties": false
    },
    "multiselect": {
      "type": "object",
      "required": ["title", "type"],
      "properties": {
        "type": {
          "type": "string",
          "enum": ["multiselect"]
        },
        "title": {
          "type": "string"
        },
        "path": {
          "type": "string"
        },
        "options": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "custom": {}
      },
      "additionalProperties": false
    },
    "array": {
      "type": "object",
      "required": ["title", "type", "items"],
      "properties": {
        "type": {
          "type": "string",
          "enum": ["array"]
        },
        "title": {
          "type": "string"
        },
        "path": {
          "type": "string"
        },
        "items": { "$ref": "#/definitions/field" },
        "custom": {}
      },
      "additionalProperties": false
    },
    "object": {
      "type": "object",
      "required": ["title", "type", "items"],
      "properties": {
        "type": {
          "type": "string",
          "enum": ["object"]
        },
        "title": {
          "type": "string"
        },
        "path": {
          "type": "string"
        },
        "items": { "$ref": "#/definitions/field" },
        "custom": {}
      },
      "additionalProperties": false
    }
  }
}

=== stoplightio/formtron/stories/examples/oas2/schema.json
{
  "$schema": "../../../../formtron-sl/ui-schema.json",
  "title": "Form (OASv2 Root Node)",
  "description": "Top-level properties of your OASv2 spec.",
  "type": "form",
  "fields": {
    "info.title": {
      "type": "string",
      "title": "Title"
    },
    "info.version": {
      "type": "string",
      "title": "Version"
    },
    "host": {
      "type": "string",
      "title": "Host",
      "required": true
    },
    "info.description": {
      "type": "markdown",
      "title": "Description"
    },
    "schemes": {
      "type": "multiselect",
      "title": "Schemes",
      "options": ["http", "https", "ws", "wss"]
    },
    "info.contact": {
      "type": "form",
      "title": "Contact",
      "description": "",
      "fields": {
        "name": {
          "type": "string",
          "title": "Name",
          "required": true
        },
        "email": {
          "type": "string",
          "title": "Email",
          "required": true
        },
        "url": {
          "type": "string",
          "title": "URL",
          "required": true
        }
      }
    },
    "info.license.name": {
      "type": "string",
      "title": "License"
    }
  }
}

=== stoplightio/formtron/stories/examples/custom-widget/schema.json
{
  "$schema": "../../../../formtron-sl/ui-schema.json",
  "title": "Form (OASv2 Operation Node)",
  "description": "An HTTP operation.",
  "type": "form",
  "fields": {
    "paths.*.?": {
      "type": "select",
      "options": ["get", "post", "put", "delete", "options"],
      "title": "Method",
      "custom": {
        "widget": "randomOption"
      }
    },
    "paths.?": {
      "type": "string",
      "title": "path",
      "required": true
    },
    "paths.*.*.tags": {
      "type": "multiselect",
      "title": "Tag",
      "custom": {
        "source": "tags"
      }
    }
  }
}
